"""changed properly

Revision ID: 232843c70b1d
Revises: f5d50b801746
Create Date: 2025-09-14 13:22:53.266512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232843c70b1d'
down_revision = 'f5d50b801746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        
        # FIX 1: Added a unique name for the foreign key constraint
        batch_op.create_foreign_key(
            "fk_pdf_chunks_user_id_user", 
            'user', 
            ['user_id'], 
            ['user_id']
        )
        
        batch_op.drop_column('pdf_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_hash', sa.VARCHAR(length=64), nullable=False))
        
        # FIX 2: Used the same unique name to identify which constraint to drop
        batch_op.drop_constraint("fk_pdf_chunks_user_id_user", type_='foreignkey')
        
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###