"""created summarized pdf content class

Revision ID: 339859378e00
Revises: 656555a971d0
Create Date: 2025-09-14 17:20:16.354443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339859378e00'
down_revision = '656555a971d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summarized_pdf_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('original_pdf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_pdf_id'], ['pdf_file.file_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pdf_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_summary', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_chunks', schema=None) as batch_op:
        batch_op.drop_column('chunk_summary')

    op.drop_table('summarized_pdf_content')
    # ### end Alembic commands ###
