"""removed markdown content column from PDFFile

Revision ID: 47c8b687147f
Revises: 1ec09de57503
Create Date: 2025-09-14 06:24:23.677984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c8b687147f'
down_revision = '1ec09de57503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.drop_column('markdown_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markdown_content', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
