"""added 2 new classes for chat messages and query cache

Revision ID: 6305cd1c0778
Revises: 8d6c32150b7a
Create Date: 2025-09-16 07:19:16.409264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6305cd1c0778'
down_revision = '8d6c32150b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('question_embedding', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_text')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['pdf_file.file_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pdf_chunks', schema=None) as batch_op:
        batch_op.drop_column('end_char')
        batch_op.drop_column('start_char')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_char', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('end_char', sa.INTEGER(), nullable=True))

    op.drop_table('chat_messages')
    op.drop_table('query_cache')
    # ### end Alembic commands ###
