"""created embeddings model

Revision ID: 88f428f93ac8
Revises: 76a7b86cc13a
Create Date: 2025-09-14 12:25:41.211737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f428f93ac8'
down_revision = '76a7b86cc13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.PickleType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['pdf_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['pdf_file.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    # ### end Alembic commands ###
