"""Initial Migrations

Revision ID: f55741955241
Revises: 84f673ff1d32
Create Date: 2025-09-13 18:48:13.315798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55741955241'
down_revision = '84f673ff1d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('markdown_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.drop_column('markdown_content')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
