"""added a new column embedding_id in PDFChunk class

Revision ID: f5d50b801746
Revises: 88f428f93ac8
Create Date: 2025-09-14 13:02:38.298033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d50b801746'
down_revision = '88f428f93ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_id', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_chunks', schema=None) as batch_op:
        batch_op.drop_column('embedding_id')

    # ### end Alembic commands ###
