"""Added 2 new columns in PDFFile , chunking strategy and embedding model

Revision ID: f9fc0e036658
Revises: 47c8b687147f
Create Date: 2025-09-14 07:56:58.073474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fc0e036658'
down_revision = '47c8b687147f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunking_strategy', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('embedding_model', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.drop_column('embedding_model')
        batch_op.drop_column('chunking_strategy')

    # ### end Alembic commands ###
